name: "Pixi-Pack Composite Action"
description: "Installs pixi via setup-pixi and then uses pixi to install and run pixi-pack."
author: "Your Name or Org"
inputs:
  source:
    description: "Path to the source (if needed by pixi-pack)"
    required: false
    default: "."
  command:
    description: "The pixi-pack command to run (e.g., build, serve, etc.)"
    required: false
    default: "build"

runs:
  using: "composite"
  steps:
    # 1) Install Pixi (using prefix-dev/setup-pixi)
    - name: Install Pixi
      uses: prefix-dev/setup-pixi@v0.0.2

    # 2) Install pixi-pack globally via pixi
    - name: Install pixi-pack
      run: pixi global install pixi-pack

    # 3) Run pixi-pack command
    - name: Run pixi-pack
      run: |
        echo "Running 'pixi-pack ${{ inputs.command }}' in source: ${{ inputs.source }}"
        cd ${{ inputs.source }}
        pixi-pack ${{ inputs.command }}

